# Set paths:
export PATH="$PATH:/usr/local/bin/"
export PATH="/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:$PATH"

# Add color to terminal:
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
